"""empty message

Revision ID: 15a2d968c5e7
Revises: eff3a5aaf41b
Create Date: 2022-10-27 10:04:02.807312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a2d968c5e7'
down_revision = 'eff3a5aaf41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('container_count_swift', sa.Integer(), nullable=True),
    sa.Column('object_count_swift', sa.Integer(), nullable=True),
    sa.Column('bytes_used_swift', mysql.BIGINT(), nullable=True),
    sa.Column('last_object', sa.String(length=255), nullable=True),
    sa.Column('count_error', sa.Integer(), nullable=True),
    sa.Column('container_count_gcp', sa.Integer(), nullable=True),
    sa.Column('object_count_gcp', sa.Integer(), nullable=True),
    sa.Column('bytes_used_gcp', mysql.BIGINT(), nullable=True),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('final_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'container_name')
    )
    op.create_index(op.f('ix_transfer_container_project_id'), 'transfer_container', ['project_id'], unique=False)
    op.create_table('transfer_container_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_error', sa.String(length=255), nullable=False),
    sa.Column('transfer_container_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_container_id'], ['transfer_container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_container_error')
    op.drop_index(op.f('ix_transfer_container_project_id'), table_name='transfer_container')
    op.drop_table('transfer_container')
    # ### end Alembic commands ###
