"""empty message

Revision ID: 4fafa4bc6d85
Revises: db4031fa2da5
Create Date: 2022-11-29 11:52:42.780788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fafa4bc6d85'
down_revision = 'db4031fa2da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project_container_hostname', ['project_id', 'container_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_container_hostname', type_='unique')
    # ### end Alembic commands ###
