"""empty message

Revision ID: 6e91a88db979
Revises: f88f17d76dad
Create Date: 2022-10-11 12:22:57.841162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e91a88db979'
down_revision = 'f88f17d76dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_container_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_error', sa.String(length=255), nullable=False),
    sa.Column('transfer_container_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_container_id'], ['transfer_container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_container_error')
    # ### end Alembic commands ###
