"""empty message

Revision ID: 707b5900c420
Revises: 
Create Date: 2022-09-30 17:26:59.199722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707b5900c420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_hostname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'hostname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_hostname')
    # ### end Alembic commands ###
