"""empty message

Revision ID: 0d15cc95e23a
Revises: 
Create Date: 2021-06-02 15:51:06.028326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d15cc95e23a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=80), nullable=False),
    sa.Column('container', sa.String(length=255), nullable=False),
    sa.Column('object', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'container', 'object', name='uk_expobj_account_container_obj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expired_object')
    # ### end Alembic commands ###
