"""empty message

Revision ID: 511d2d012f7e
Revises: 
Create Date: 2021-06-01 17:57:36.983657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511d2d012f7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=80), nullable=False),
    sa.Column('container', sa.String(length=255), nullable=False),
    sa.Column('object', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expired_object')
    # ### end Alembic commands ###
