"""empty message

Revision ID: a70e110bd501
Revises: 
Create Date: 2026-07-30 09:01:52.345397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70e110bd501'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_container_paginated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=False),
    sa.Column('marker', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('object_count_swift', sa.Integer(), nullable=True),
    sa.Column('bytes_used_swift', sa.BigInteger(), nullable=True),
    sa.Column('count_error', sa.Integer(), nullable=True),
    sa.Column('object_count_gcp', sa.Integer(), nullable=True),
    sa.Column('bytes_used_gcp', sa.BigInteger(), nullable=True),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('final_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'container_name', 'marker')
    )
    with op.batch_alter_table('transfer_container_paginated', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_container_paginated_project_id'), ['project_id'], unique=False)

    op.create_table('transfer_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('container_count_swift', sa.Integer(), nullable=True),
    sa.Column('object_count_swift', sa.Integer(), nullable=True),
    sa.Column('bytes_used_swift', sa.BigInteger(), nullable=True),
    sa.Column('last_object', sa.String(length=255), nullable=True),
    sa.Column('count_error', sa.Integer(), nullable=True),
    sa.Column('container_count_gcp', sa.Integer(), nullable=True),
    sa.Column('object_count_gcp', sa.Integer(), nullable=True),
    sa.Column('bytes_used_gcp', sa.BigInteger(), nullable=True),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('final_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('transfer_container_paginated_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_error', sa.String(length=255), nullable=False),
    sa.Column('transfer_container_paginated_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_container_paginated_id'], ['transfer_container_paginated.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_project_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_error', sa.String(length=255), nullable=False),
    sa.Column('transfer_project_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_project_id'], ['transfer_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_project_error')
    op.drop_table('transfer_container_paginated_error')
    op.drop_table('transfer_project')
    with op.batch_alter_table('transfer_container_paginated', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_container_paginated_project_id'))

    op.drop_table('transfer_container_paginated')
    # ### end Alembic commands ###
