"""empty message

Revision ID: ea38c0e8e1f9
Revises: 29cd99afa4d4
Create Date: 2021-07-26 13:19:15.323864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea38c0e8e1f9'
down_revision = '29cd99afa4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_project_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_error', sa.String(length=255), nullable=False),
    sa.Column('transfer_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_project_id'], ['transfer_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('project_id', table_name='container_info')
    op.create_unique_constraint(None, 'container_info', ['project_id', 'container_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'container_info', type_='unique')
    op.create_index('project_id', 'container_info', ['project_id'], unique=True)
    op.drop_table('transfer_project_error')
    # ### end Alembic commands ###
