"""empty message

Revision ID: f0d66bb9d46b
Revises: ea38c0e8e1f9
Create Date: 2021-08-16 13:33:11.580532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d66bb9d46b'
down_revision = 'ea38c0e8e1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_project_error', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_project_error', 'created')
    # ### end Alembic commands ###
